/*******************************************************************
        SYSTEM cipsystem
        Module for PROCESS alarmButton
        Filename: alarmButton.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        		naming option: channel name prefix
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mDoorControlUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_alarmButton.write_access_
#define STATUS (pStatus_alarmButton->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_alarmButton
	{normal = 1};

enum eSTATES_alarmButton
	{Pressed = 1, Released};


/* External Declarations */

extern unsigned char time_;
extern struct tCHNOUT_mDoorControlUnit CHNOUT_mDoorControlUnit;
void fUPDATE_DoorControlSystem (void);
int fPULSE_alarmToggler (enum eOUTPLS_ name_);

/* Global Declarations */

union tSTATUS_alarmButton status_alarmButton;
const union tSTATUS_alarmButton *pStatus_alarmButton = &status_alarmButton;

/* Function Prototypes */

void IN_button2InChannel_press (void);
void IN_button2InChannel_release (void);
void fINIT_alarmButton (void);

/* Input Channel Functions */

void IN_button2InChannel_press (void)
{
	switch(status_alarmButton.read_access_.STATE)
	{
	case Released:
	 	{
	 		/* OPERATIONS before writing */
	 		/* opx */
	 		{ }
	 		status_alarmButton.write_access_.STATE = Pressed;
	 		fPULSE_alarmToggler (O21_pressed);
	 	}
		break;
	default:
		return;
	}
	fUPDATE_DoorControlSystem ();
	return;
}
void IN_button2InChannel_release (void)
{
	switch(status_alarmButton.read_access_.STATE)
	{
	case Pressed:
	 	status_alarmButton.write_access_.STATE = Released;
		break;
	default:
		return;
	}
	fUPDATE_DoorControlSystem ();
	return;
}		
/* Process Initialization Function */

void fINIT_alarmButton (void)
{
	status_alarmButton.write_access_.STATE = Released;
}		

/*********************************************************************
	End of Module for PROCESS alarmButton
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236c9-5df2-11e4-b3d8-533ac356fef7,632d07b4-462f-11e4-8d10-617b527355dd,eb661e07-761b-11e4-9ea4-f90149ada069,ifPUpYHjsRMnEO2uPNnsEpJcT8Y=] */
