/*******************************************************************
        SYSTEM cipsystem
        Module for PROCESS alarmToggler
        Filename: alarmToggler.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        		naming option: channel name prefix
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mDoorControlUnit.h"

/* Process Macro Definitions */

#define SELF status_alarmToggler.write_access_
#define STATUS (pStatus_alarmToggler->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_alarmToggler
	{normal = 1};

enum eSTATES_alarmToggler
	{Off = 1, On};

enum eINPULS_alarmToggler
	{IP_change = 6};
	

/* External Declarations */

extern unsigned char time_;
extern struct tCHNOUT_mDoorControlUnit CHNOUT_mDoorControlUnit;
void fUPDATE_DoorControlSystem (void);
int fPULSE_alarmLight (enum eOUTPLS_ name_);
int fPULSE_doorControl (enum eOUTPLS_ name_);

/* Global Declarations */

union tSTATUS_alarmToggler status_alarmToggler;
const union tSTATUS_alarmToggler *pStatus_alarmToggler = &status_alarmToggler;

/* Function Prototypes */

int fPULSE_alarmToggler (enum eOUTPLS_ name_);
void fINIT_alarmToggler (void);

/* Input Channel Functions */

int fPULSE_alarmToggler (enum eOUTPLS_ name_)
{
	switch(name_)
	{
		/* INPULSE change */
	case O21_pressed:		/* PULSE CAST from PROCESS alarmButton */
		switch(status_alarmToggler.read_access_.STATE)
		{
		case Off:
			status_alarmToggler.write_access_.STATE = On;
			fPULSE_alarmLight (O22_on);
			fPULSE_doorControl (O22_on);
			break;
		case On:
			status_alarmToggler.write_access_.STATE = Off;
			fPULSE_alarmLight (O22_off);
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_alarmToggler (void)
{
	status_alarmToggler.write_access_.STATE = Off;
}		

/*********************************************************************
	End of Module for PROCESS alarmToggler
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236c9-5df2-11e4-b3d8-533ac356fef7,632d07b4-462f-11e4-8d10-617b527355dd,feb47a95-761c-11e4-9ea4-f90149ada069,AqUTtKVqQhf2HcVqIEwW1squQHA=] */
