/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplTarget
	Error Header File for CIP MACHINE mDoorControlUnit
	Filename: eDoorControlUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_eDoorControlUnit_h_)
	#define _eDoorControlUnit_h_

/* Include Files */

#include "mDoorControlUnit.h"

#endif // _eDoorControlUnit_h_

/*********************************************************************
	End of Error Header File for CIP MACHINE mDoorControlUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236c9-5df2-11e4-b3d8-533ac356fef7,iJEcNnRJ4Mdo+5v0kHH8h9PuazY=] */
