/*******************************************************************
        SYSTEM cipsystem
        Module for PROCESS light1
        Filename: light1.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        		naming option: channel name prefix
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mDoorControlUnit.h"

/* Process Macro Definitions */

#define SELF status_light1.write_access_
#define STATUS (pStatus_light1->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_light1
	{normal = 1};

enum eSTATES_light1
	{Off = 1, On};

enum eINPULS_light1
	{IP_on = 1, IP_off = 2};
	

/* External Declarations */

extern unsigned char time_;
extern struct tCHNOUT_mDoorControlUnit CHNOUT_mDoorControlUnit;
void fUPDATE_DoorControlSystem (void);

/* Global Declarations */

union tSTATUS_light1 status_light1;
const union tSTATUS_light1 *pStatus_light1 = &status_light1;

/* Function Prototypes */

int fPULSE_light1 (enum eOUTPLS_ name_);
void fINIT_light1 (void);

/* Input Channel Functions */

int fPULSE_light1 (enum eOUTPLS_ name_)
{
	switch(name_)
	{
		/* INPULSE on */
	case O19_on:		/* PULSE CAST from PROCESS blinker */
	case O18_startOpening:		/* PULSE CAST from PROCESS door */
		switch(status_light1.read_access_.STATE)
		{
		case Off:
			status_light1.write_access_.STATE = On;
			CHNOUT_mDoorControlUnit.message_.CHAN_light1OutChannel.name_ = light1OutChannel_on;
			OUT_light1OutChannel_on();
			break;
		default:
			break;
		}
		break;
		/* INPULSE off */
	case O19_off:		/* PULSE CAST from PROCESS blinker */
		switch(status_light1.read_access_.STATE)
		{
		case On:
			status_light1.write_access_.STATE = Off;
			CHNOUT_mDoorControlUnit.message_.CHAN_light1OutChannel.name_ = light1OutChannel_off;
			OUT_light1OutChannel_off();
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_light1 (void)
{
	status_light1.write_access_.STATE = Off;
}		

/*********************************************************************
	End of Module for PROCESS light1
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236c9-5df2-11e4-b3d8-533ac356fef7,632d07b4-462f-11e4-8d10-617b527355dd,7cc9e916-4715-11e4-9cbe-892401a00ca4,dhvEUVD65xqeXxBtIOv6/33n1LY=] */
