/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplTarget
	Header File for CIP MACHINE mDoorControlUnit
	Filename: mDoorControlUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_mDoorControlUnit_h_)
	#define _mDoorControlUnit_h_

/* Include Files */

#include <stdlib.h>
#include "sDoorControlUnit.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Constants */

#define TICKS_PER_SECOND 10
#define _500ms TICKS_PER_SECOND/2

/* User Types */

typedef int tProdNr;

/* Timer Types*/

#if !defined(TIMER_C_COUNT_)
	#define TIMER_C_COUNT_ 1
#endif // TIMER_C_COUNT_

#if !defined(_eTIMER__)
	#define _eTIMER__

	enum _eTIMER_
		{TIMER_blinker_19, TIMER_doorControl_6, TIMER_COUNT_};

#endif // _eTIMER__

/* Outpulse Types */
 
#if !defined(_eOUTPLS__)
	#define _eOUTPLS__

	enum eOUTPLS_
		{O6_doorOpen = 6, O6_doorClose = 7, O6_lightBarrierOn = 13, O2_pressed = 1, 
		 O2_released = 2, O21_pressed = 16, O21_released = 17, O19_on = 9, O19_off = 10, 
		 O22_off = 18, O22_on = 19, O18_opened = 5, O18_startClosing = 11, 
		 O18_startOpening = 12, O18_closed = 8, O20_cleared = 14, 
		 O20_interrupted = 15};

#endif // _eOUTPLS__

struct tOUTPLS_doorControl
{
	enum eOUTPLS_ name_;
};

struct tOUTPLS_openButton
{
	enum eOUTPLS_ name_;
};

struct tOUTPLS_alarmButton
{
	enum eOUTPLS_ name_;
};

struct tOUTPLS_blinker
{
	enum eOUTPLS_ name_;
};

struct tOUTPLS_alarmToggler
{
	enum eOUTPLS_ name_;
};

struct tOUTPLS_door
{
	enum eOUTPLS_ name_;
};

struct tOUTPLS_lightBarrier
{
	enum eOUTPLS_ name_;
};

union tOUTPLS_DoorControlSystem
{
	struct tOUTPLS_doorControl OUTPLS_doorControl;
	struct tOUTPLS_openButton OUTPLS_openButton;
	struct tOUTPLS_alarmButton OUTPLS_alarmButton;
	struct tOUTPLS_blinker OUTPLS_blinker;
	struct tOUTPLS_alarmToggler OUTPLS_alarmToggler;
	struct tOUTPLS_door OUTPLS_door;
	struct tOUTPLS_lightBarrier OUTPLS_lightBarrier;
};

/* Global Output Type */

struct tCHAN_driveOutChannel
{
	enum eMSG_driveOutChannel name_;
};

struct tCHAN_light1OutChannel
{
	enum eMSG_light1OutChannel name_;
};

struct tCHAN_light2OutChannel
{
	enum eMSG_light2OutChannel name_;
};

struct tCHAN_lightBarrierOutChannel
{
	enum eMSG_lightBarrierOutChannel name_;
};

union tCHAN_mDoorControlUnit
{
	struct tCHAN_driveOutChannel CHAN_driveOutChannel;
	struct tCHAN_light1OutChannel CHAN_light1OutChannel;
	struct tCHAN_light2OutChannel CHAN_light2OutChannel;
	struct tCHAN_lightBarrierOutChannel CHAN_lightBarrierOutChannel;
};

struct tCHNOUT_mDoorControlUnit
{
	union tCHAN_mDoorControlUnit message_;
};

/* Timer- and Queue-Element */

struct tTMEL_mDoorControlUnit
{
	unsigned char set_; /* Boolean */
	unsigned char end_;
};

struct tTMQE_mDoorControlUnit
{
	struct tTMQE_mDoorControlUnit *preced_;
	struct tTMQE_mDoorControlUnit *next_;
	int proctype_;
};

/* Global Table Elements */
struct tTIMING_mDoorControlUnit
{
	void  (*tkhndl_) (void);
	void (*tuhndl_)(void);
	int  set_;
};

/* Types for Process doorControl */

struct tPRSTAT_doorControl
{
	int STATE;
};

union tSTATUS_doorControl
{
	struct tPRSTAT_doorControl write_access_;
	struct tPRSTAT_doorControl read_access_;
};

struct tPRINST_doorControl
{
	struct tTMEL_mDoorControlUnit timer_;
	struct tTMQE_mDoorControlUnit timeup_;
};

/* Types for Process openButton */

struct tPRSTAT_openButton
{
	int STATE;
};

union tSTATUS_openButton
{
	struct tPRSTAT_openButton write_access_;
	struct tPRSTAT_openButton read_access_;
};

/* Types for Process alarmButton */

struct tPRSTAT_alarmButton
{
	int STATE;
};

union tSTATUS_alarmButton
{
	struct tPRSTAT_alarmButton write_access_;
	struct tPRSTAT_alarmButton read_access_;
};

/* Types for Process light1 */

struct tPRSTAT_light1
{
	int STATE;
};

union tSTATUS_light1
{
	struct tPRSTAT_light1 write_access_;
	struct tPRSTAT_light1 read_access_;
};

/* Types for Process alarmLight */

struct tPRSTAT_alarmLight
{
	int STATE;
};

union tSTATUS_alarmLight
{
	struct tPRSTAT_alarmLight write_access_;
	struct tPRSTAT_alarmLight read_access_;
};

/* Types for Process blinker */

struct tPRSTAT_blinker
{
	int STATE;
	unsigned int halfPeriod;
};

union tSTATUS_blinker
{
	struct tPRSTAT_blinker write_access_;
	struct tPRSTAT_blinker read_access_;
};

struct tPRINST_blinker
{
	struct tTMEL_mDoorControlUnit timer_;
	struct tTMQE_mDoorControlUnit timeup_;
};

/* Types for Process alarmToggler */

struct tPRSTAT_alarmToggler
{
	int STATE;
};

union tSTATUS_alarmToggler
{
	struct tPRSTAT_alarmToggler write_access_;
	struct tPRSTAT_alarmToggler read_access_;
};

/* Types for Process door */

struct tPRSTAT_door
{
	int STATE;
};

union tSTATUS_door
{
	struct tPRSTAT_door write_access_;
	struct tPRSTAT_door read_access_;
};

/* Types for Process lightBarrier */

struct tPRSTAT_lightBarrier
{
	int STATE;
};

union tSTATUS_lightBarrier
{
	struct tPRSTAT_lightBarrier write_access_;
	struct tPRSTAT_lightBarrier read_access_;
};

#endif // _mDoorControlUnit_h_

/*********************************************************************
	End of Header File for CIP MACHINE mDoorControlUnit
*********************************************************************/
/* Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236ca-5df2-11e4-b3d8-533ac356fef7,3d1236c9-5df2-11e4-b3d8-533ac356fef7,uNGUXyaMjHlbZsruW7sDPPTk07M=] */
