/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplTarget
	Module for CIP MACHINE mDoorControlUnit
	Filename: mDoorControlUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mDoorControlUnit.h"

/* External Declarations */

void fINIT_alarmButton (void);
void fINIT_alarmLight (void);
void fINIT_alarmToggler (void);
void fINIT_blinker (void);
void fINIT_door (void);
void fINIT_doorControl (void);
void fINIT_light1 (void);
void fINIT_lightBarrier (void);
void fINIT_openButton (void);

/* Global Declarations */

unsigned char time_ = 0;
struct tCHNOUT_mDoorControlUnit CHNOUT_mDoorControlUnit;
struct tTIMING_mDoorControlUnit TIMING_mDoorControlUnit[TIMER_COUNT_];
struct tTMQE_mDoorControlUnit *tuhead_mDoorControlUnit, *tutail_mDoorControlUnit;

/* Function Prototypes */

void fSETTIM_mDoorControlUnit (unsigned char *delay_, struct tTMEL_mDoorControlUnit *timer_, struct tTMQE_mDoorControlUnit *timeup_);
void fSTOPTIM_mDoorControlUnit (struct tTMEL_mDoorControlUnit *timer_, struct tTMQE_mDoorControlUnit *timeup_);
void fUPDATE_DoorControlSystem (void);

/* AUTO_ Handler Function */

void TRG_AUTO_(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

void TRG_TICK_(void)
{
	int i_;
	++time_;
	for (i_ = 0; i_ < 2; i_ ++)
	{
		if (TIMING_mDoorControlUnit[i_].set_)
		{
			TIMING_mDoorControlUnit[i_].tkhndl_();
		}
	}
	TRG_PENDING_.TIMEUP_ = tuhead_mDoorControlUnit != 0;
	TRG_PENDING_.ANY_ = TRG_PENDING_.ANY_ || TRG_PENDING_.TIMEUP_;
}

void fSETTIM_mDoorControlUnit (unsigned char *delay_, struct tTMEL_mDoorControlUnit *timer_, struct tTMQE_mDoorControlUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (!timer_->set_)
		{
			++TIMING_mDoorControlUnit[timeup_->proctype_].set_;
		}
		timer_->set_ = TRUE;
		timer_->end_ = time_ + *delay_;
		if (tuhead_mDoorControlUnit == timeup_)
		{
			tuhead_mDoorControlUnit = tuhead_mDoorControlUnit->next_;
		}
		if (timeup_->preced_)
		{
			timeup_->preced_->next_ = timeup_->next_;
		}
		if (timeup_->next_)
		{
			timeup_->next_->preced_ = timeup_->preced_;
		}
		if (tutail_mDoorControlUnit == timeup_)
		{
			tutail_mDoorControlUnit = timeup_->preced_;
		}
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
		{
			--TIMING_mDoorControlUnit[timeup_->proctype_].set_;
		}
		timer_->set_ = FALSE;
		if (tuhead_mDoorControlUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (!tuhead_mDoorControlUnit)
			{
				tuhead_mDoorControlUnit = tutail_mDoorControlUnit = timeup_;
			}
			else 
			{
				tutail_mDoorControlUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mDoorControlUnit;
				tutail_mDoorControlUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mDoorControlUnit (struct tTMEL_mDoorControlUnit *timer_, struct tTMQE_mDoorControlUnit *timeup_)
{
	if (timer_->set_)
	{
		--TIMING_mDoorControlUnit[timeup_->proctype_].set_;
	}
	timer_->set_ = FALSE;
	if (tuhead_mDoorControlUnit == timeup_)
	{
		tuhead_mDoorControlUnit = tuhead_mDoorControlUnit->next_;
	}
	if (timeup_->preced_)
	{
		timeup_->preced_->next_ = timeup_->next_;
	}
	if (timeup_->next_)
	{
		timeup_->next_->preced_ = timeup_->preced_;
	}
	if (tutail_mDoorControlUnit == timeup_)
	{
		tutail_mDoorControlUnit = timeup_->preced_;
	}
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void TRG_STEP_(void)
{
	if (tuhead_mDoorControlUnit != 0)
	{
		TIMING_mDoorControlUnit[tuhead_mDoorControlUnit->proctype_].tuhndl_();
	}
	return;
}

	/* Chain Function for CIP Machine */

void TRG_CHAIN_(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void TRG_TIMEUP_(void)
{
	if (tuhead_mDoorControlUnit != 0)
	{
		TIMING_mDoorControlUnit[tuhead_mDoorControlUnit->proctype_].tuhndl_();
	}
	return;
}

	/* Read Function for CIP Machine */

void TRG_READ_(void)
{
	return;
}

/* Update Functions */

void fUPDATE_DoorControlSystem (void)
{
	TRG_PENDING_.TIMEUP_ = tuhead_mDoorControlUnit != 0;
	TRG_PENDING_.ANY_ = 
		TRG_PENDING_.TIMEUP_;
}

/* Initialization Function */

int fINIT_(void)
{
	tuhead_mDoorControlUnit = tutail_mDoorControlUnit = 0;
	TRG_PENDING_.ANY_ = 0;
	TRG_PENDING_.CHAIN_ = 0;
	TRG_PENDING_.TIMEUP_ = 0;
	TRG_PENDING_.READ_ = 0;
	TRG_PENDING_.AUTO_ = 0;
	fINIT_alarmButton ();
	fINIT_alarmLight ();
	fINIT_alarmToggler ();
	fINIT_blinker ();
	fINIT_door ();
	fINIT_doorControl ();
	fINIT_light1 ();
	fINIT_lightBarrier ();
	fINIT_openButton ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mDoorControlUnit
*********************************************************************/

/* Actifsource ID=[a9fcef86-9d17-11e1-90e4-e1fd5739c0f6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236ca-5df2-11e4-b3d8-533ac356fef7,3d1236c9-5df2-11e4-b3d8-533ac356fef7,zbjlEoqBIWu+nOzltdmwy8rOZVU=] */
