/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplTarget
	Module for CIP SHELL sDoorControlUnit
	Filename: sDoorControlUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "sDoorControlUnit.h"

/* Pending Interface Variable */

struct tPENDING_ TRG_PENDING_;

/*********************************************************************
	End of Module for CIP SHELL sDoorControlUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236c9-5df2-11e4-b3d8-533ac356fef7,3d1236ca-5df2-11e4-b3d8-533ac356fef7,QHwFwCM3yGp8SjiOjCtGNW4oIX4=] */
