/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplTarget
	Trace Interface Module for CIP MACHINE mDoorControlUnit
	Filename: tDoorControlUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "tDoorControlUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mDoorControlUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,3d1236cd-5df2-11e4-b3d8-533ac356fef7,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,3d1236c9-5df2-11e4-b3d8-533ac356fef7,Exwgz/W5ActqOHH2mHd5pHf+qnI=] */
