/*******************************************************************
        SYSTEM cipsystem
        Module for PROCESS alarmLight
        Filename: alarmLight.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        		naming option: channel name prefix
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mDoorControlUnit.h"

/* Process Macro Definitions */

#define SELF status_alarmLight.write_access_
#define STATUS (pStatus_alarmLight->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_alarmLight
	{normal = 1};

enum eSTATES_alarmLight
	{Off = 1, On};

enum eINPULS_alarmLight
	{IP_on = 1, IP_off = 2};
	

/* External Declarations */

extern unsigned char time_;
extern struct tCHNOUT_mDoorControlUnit CHNOUT_mDoorControlUnit;
void fUPDATE_DoorControlSystem (void);

/* Global Declarations */

union tSTATUS_alarmLight status_alarmLight;
const union tSTATUS_alarmLight *pStatus_alarmLight = &status_alarmLight;

/* Function Prototypes */

int fPULSE_alarmLight (enum eOUTPLS_ name_);
void fINIT_alarmLight (void);

/* Input Channel Functions */

int fPULSE_alarmLight (enum eOUTPLS_ name_)
{
	switch(name_)
	{
		/* INPULSE on */
	case O22_on:		/* PULSE CAST from PROCESS alarmToggler */
		switch(status_alarmLight.read_access_.STATE)
		{
		case Off:
			status_alarmLight.write_access_.STATE = On;
			CHNOUT_mDoorControlUnit.message_.CHAN_light2OutChannel.name_ = light2OutChannel_on;
			OUT_light2OutChannel_on();
			break;
		default:
			break;
		}
		break;
		/* INPULSE off */
	case O22_off:		/* PULSE CAST from PROCESS alarmToggler */
		switch(status_alarmLight.read_access_.STATE)
		{
		case On:
			status_alarmLight.write_access_.STATE = Off;
			CHNOUT_mDoorControlUnit.message_.CHAN_light2OutChannel.name_ = light2OutChannel_off;
			OUT_light2OutChannel_off();
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_alarmLight (void)
{
	status_alarmLight.write_access_.STATE = Off;
}		

/*********************************************************************
	End of Module for PROCESS alarmLight
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,632d07b4-462f-11e4-8d10-617b527355dd,e0cfee53-761d-11e4-9ea4-f90149ada069,bdQd+flB0VhJH9Q1urTMSP/+3uQ=] */
