/*******************************************************************
        SYSTEM cipsystem
        Module for PROCESS door
        Filename: door.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        		naming option: channel name prefix
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mDoorControlUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_door.write_access_
#define STATUS (pStatus_door->read_access_)
#define TIME time_
#define toOpen() TRTAB_toOpen \
	[status_doorControl.read_access_.STATE - 1] != 0
#define toClose() TRTAB_toClose \
	[status_doorControl.read_access_.STATE - 1] != 0

/* Process Enumerations */

enum eMODES_door
	{normal = 1};

enum eSTATES_door
	{Closed = 1, Closing, Opened, Opening, StartClosing, StartOpening};

enum eINPULS_door
	{IP_open = 7, IP_close = 10};
	

/* External Declarations */

extern unsigned char time_;
extern struct tCHNOUT_mDoorControlUnit CHNOUT_mDoorControlUnit;
extern union tSTATUS_doorControl status_doorControl;
void fUPDATE_DoorControlSystem (void);
int fPULSE_blinker (enum eOUTPLS_ name_);
int fPULSE_light1 (enum eOUTPLS_ name_);
int fPULSE_lightBarrier (enum eOUTPLS_ name_);
int fPULSE_doorControl (enum eOUTPLS_ name_);

/* Global Declarations */

union tSTATUS_door status_door;
const union tSTATUS_door *pStatus_door = &status_door;
const static unsigned char TRTAB_toOpen[4] =      /* [doorControl states] */
	{0, 0, 0, 1};

const static unsigned char TRTAB_toClose[4] =      /* [doorControl states] */
	{0, 0, 1, 0};


/* Function Prototypes */

void IN_doorInChannel_doorOpened (void);
void IN_doorInChannel_doorClosed (void);
void IN_doorInChannel_doorNotClosed (void);
void IN_doorInChannel_doorNotOpened (void);
int fPULSE_door (enum eOUTPLS_ name_);
void fINIT_door (void);

/* Input Channel Functions */

void IN_doorInChannel_doorOpened (void)
{
	switch(status_door.read_access_.STATE)
	{
	case Opening:
	 	status_door.write_access_.STATE = Opened;
	 	CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_stop;
	 	OUT_driveOutChannel_stop();
	 	fPULSE_lightBarrier (O18_opened);
	 	fPULSE_doorControl (O18_opened);
		break;
	default:
		return;
	}
	fUPDATE_DoorControlSystem ();
	return;
}
void IN_doorInChannel_doorClosed (void)
{
	switch(status_door.read_access_.STATE)
	{
	case Closing:
	 	status_door.write_access_.STATE = Closed;
	 	CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_stop;
	 	OUT_driveOutChannel_stop();
	 	fPULSE_blinker (O18_closed);
	 	fPULSE_lightBarrier (O18_closed);
		break;
	case Opening:
	 	status_door.write_access_.STATE = StartOpening;
		break;
	default:
		return;
	}
	fUPDATE_DoorControlSystem ();
	return;
}
void IN_doorInChannel_doorNotClosed (void)
{
	switch(status_door.read_access_.STATE)
	{
	case Closed:
	 	status_door.write_access_.STATE = Closing;
	 	CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_close;
	 	OUT_driveOutChannel_close();
	 	fPULSE_blinker (O18_startClosing);
		break;
	case StartOpening:
		if (toClose())
		{
			status_door.write_access_.STATE = Closing;
			CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_close;
			OUT_driveOutChannel_close();
		}
		else
		{
			status_door.write_access_.STATE = Opening;
		}
		break;
	default:
		return;
	}
	fUPDATE_DoorControlSystem ();
	return;
}
void IN_doorInChannel_doorNotOpened (void)
{
	switch(status_door.read_access_.STATE)
	{
	case StartClosing:
		if (toOpen())
		{
			status_door.write_access_.STATE = Opening;
			CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_open;
			OUT_driveOutChannel_open();
		}
		else
		{
			status_door.write_access_.STATE = Closing;
		}
		break;
	default:
		return;
	}
	fUPDATE_DoorControlSystem ();
	return;
}		
int fPULSE_door (enum eOUTPLS_ name_)
{
	switch(name_)
	{
		/* INPULSE open */
	case O6_doorOpen:		/* PULSE CAST from PROCESS doorControl */
		switch(status_door.read_access_.STATE)
		{
		case Closed:
			status_door.write_access_.STATE = StartOpening;
			CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_open;
			OUT_driveOutChannel_open();
			fPULSE_light1 (O18_startOpening);
			break;
		case Closing:
			status_door.write_access_.STATE = Opening;
			CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_open;
			OUT_driveOutChannel_open();
			fPULSE_light1 (O18_startOpening);
			break;
		default:
			break;
		}
		break;
		/* INPULSE close */
	case O6_doorClose:		/* PULSE CAST from PROCESS doorControl */
		switch(status_door.read_access_.STATE)
		{
		case Opened:
			status_door.write_access_.STATE = StartClosing;
			CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_close;
			OUT_driveOutChannel_close();
			fPULSE_blinker (O18_startClosing);
			break;
		case Opening:
			status_door.write_access_.STATE = Closing;
			CHNOUT_mDoorControlUnit.message_.CHAN_driveOutChannel.name_ = driveOutChannel_close;
			OUT_driveOutChannel_close();
			fPULSE_blinker (O18_startClosing);
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_door (void)
{
	status_door.write_access_.STATE = Closed;
}		

/*********************************************************************
	End of Module for PROCESS door
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,632d07b4-462f-11e4-8d10-617b527355dd,2940bf3c-5dcf-11e4-963d-dbfaab6e834b,xr2UwIj2s8OEHbJqGaZV2TK8byc=] */
