/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplHost
	Error Header File for CIP MACHINE mDoorControlUnit
	Filename: eDoorControlUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_eDoorControlUnit_h_)
	#define _eDoorControlUnit_h_

/* Include Files */

#include "mDoorControlUnit.h"

#endif // _eDoorControlUnit_h_

/*********************************************************************
	End of Error Header File for CIP MACHINE mDoorControlUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,ePDl53CJ7PQpuq3H7vfD/vBYfOI=] */
