/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplHost
	Error Interface Module for CIP MACHINE mDoorControlUnit
	Filename: eDoorControlUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "eDoorControlUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mDoorControlUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,+6LWUUrN0YoXX2xwtHl99j/BUXY=] */
