/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplHost
	Module for CIP SHELL sDoorControlUnit
	Filename: sDoorControlUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "sDoorControlUnit.h"

/* Pending Interface Variable */

struct tPENDING_ TRG_PENDING_;

/*********************************************************************
	End of Module for CIP SHELL sDoorControlUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,79091603-4728-11e4-aefa-c3efe9fa99c0,CmNfF0m5CL9LdCam3MZXoDS5Yrc=] */
