/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION DoorControlSystemImplHost
	Trace Interface Module for CIP MACHINE mDoorControlUnit
	Filename: tDoorControlUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "tDoorControlUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mDoorControlUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,+kuhkudHoZNQYubPIORQ73RMZtw=] */
