/*********************************************************************
	SYSTEM cipsystem
	IMPLEMENTATION  DoorControlSystemImplHost
	Trace Interface Header File for CIP MACHINE mDoorControlUnit
	Filename: tDoorControlUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
			naming option: channel name prefix
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_tDoorControlUnit_h_)
	#define _tDoorControlUnit_h_

/* Text Switch Constants */

#if defined(_TRACE__)
	#undef _TRACE__
#endif

#if defined(_UT_INPUT_)
	#undef _UT_INPUT_
#endif

#if defined(_UT_OUTPUT_)
	#undef _UT_OUTPUT_
#endif

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mDoorControlUnit.h"

#endif // _tDoorControlUnit_h_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mDoorControlUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,79056c7a-4728-11e4-aefa-c3efe9fa99c0,cca6c98c-462e-11e4-8d10-617b527355dd,5bf79245-4729-11e4-aefa-c3efe9fa99c0,790879be-4728-11e4-aefa-c3efe9fa99c0,L7xkJGow60ZCyheYRqMks1jHHCo=] */
